---
- name: "Unarchive backend js files"
  become: yes
  unarchive:
    src: /root/project/backend.tar.gz
    dest: .

- name: Stop pm2
  command: |
    pm2 ls
    pm2 stop backend
    pm2 delete backend
    pm2 logs
  ignore_errors: yes

- name: Build node service
  become: yes
  command: |
    pwd
    ls
    cd backend
    npm i
    npm run build
    npm run start:prod

- name: Run backend using pm2
  command: |
    pm2 start npm --name backend -- start