---
- name: "Unarchive backend js files"
  become: yes
  unarchive:
    src: /root/project/backend.tar.gz
    dest: .

#- name: Stop pm2
#  command: |
#    pm2 stop backend
#    pm2 delete backend
#  ignore_errors: yes

- name: Build node service and run backend using pm2
  become: yes
  command: |
    pwd
    ls
    cd backend
    npm i
    npm run build
    npm run prestart:prod
    pm2 start npm --name backend -- start